# Generated by Django 3.1.3 on 2020-11-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201102_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmaterials',
            name='particular',
            field=models.CharField(default='Hello', max_length=250),
        ),
    ]
