# Generated by Django 3.1.3 on 2020-12-03 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201102_1023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainMaterials',
            new_name='MainMaterial',
        ),
        migrations.CreateModel(
            name='SpunPOITransformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='SpunPOIHtLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Ltlineipset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Ltlinedomestic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='IpSet63KvaTransformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='IpSet63KvaLtLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='IpSet63KvaHtLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='IpSet25KvaTransformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='IpSet25KvaLtLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='IpSet25KvaHtLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='IpSet100KvaTransformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='IpSet100KvaLtLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='IpSet100KvaHtLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ExtenTransLtLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ExtenTransformerCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ExtenHtLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalDTCTransformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalDTCHtLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainmaterial')),
            ],
        ),
    ]
